### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by burntsugar** [burntsugar/WestMacsAppCoreCS#1]
- [ ] Implement Serialization classes for Place types.
- [ ] Implement Coords class.
- [ ] Sort distance from west.
- [ ] Implement SurfaceWater class
- [ ] Consider the future of Place as interface, or as an abstract class. I have left Place as an interface for now as I develop the design of the implementing class. This gives some flexibility should I decide to switch it out/in as an abstract class.
